CREATE DATABASE ClubFinder;

CREATE TABLE IF NOT EXISTS Club (
    ClubID SMALLINT UNSIGNED UNIQUE NOT NULL,
    ClubName VARCHAR(100) UNIQUE NOT NULL,
    DateLastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Complete BIT NOT NULL,
    PRIMARY KEY(ClubID, ClubName)
);

CREATE TABLE IF NOT EXISTS Contacts (
    ClubID SMALLINT UNSIGNED UNIQUE NOT NULL,
    ClubContact VARCHAR(50),
    OfficerFirstName VARCHAR(50) NOT NULL,
    OfficerLastName VARCHAR(50) NOT NULL,
    OfficerContact VARCHAR(50) NOT NULL,
    FOREIGN KEY (ClubID) REFERENCES Club(ClubID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Websites (
    ClubID SMALLINT UNSIGNED NOT NULL,
    URL VARCHAR(200),
    Instagram BIT,
    FOREIGN KEY (ClubID) REFERENCES Club(ClubID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Description (
    ClubID SMALLINT UNSIGNED UNIQUE NOT NULL,
    Description VARCHAR(15000) NOT NULL,
    FOREIGN KEY (ClubID) REFERENCES Club(ClubID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS MeetingTimes (
    ClubID SMALLINT UNSIGNED NOT NULL,
    DayOfWeek VARCHAR(10),
    StartTime TIME,
    EndTime TIME,
    Location VARCHAR(150),
    FOREIGN KEY (ClubID) REFERENCES Club(ClubID) ON DELETE CASCADE ON UPDATE CASCADE
);